### ISSUE TITLE
로그인 전 설정 버튼 클릭시 이슈-[page routing, broken GitHub icon] 

### ISSUE THREAD

**Issue by DENGARDEN** [skkuse/2022fall_41class_team2#22]
![image](https://user-images.githubusercontent.com/54666446/199660656-81662b0d-8adc-4238-87ef-ba93d82a930e.png)

http://localhost:3003/auth/login

**Comment by bw-99** [comment]
setting 페이지를 private route(로그인 유저만 이용 가능)으로 설정하여 그렇습니다.
setting을 public으로 변경할까요?

**Comment by DENGARDEN** [comment]
setting을 private route로 설정하는 방향으로 가는 게 맞는 것 같습니다. 아이콘 깨지는 것만 제가 지금 수정해놓겠습니다!

**Comment by bw-99** [comment]
아아 넵 알겠습니다!
