### ISSUE TITLE
repos API 동작 오류

### ISSUE THREAD

**Issue by bw-99** [skkuse/2022fall_41class_team2#43]
GET repos/ 요청 시 -> results: [] 인 상황에서,

repo를 채우기 위해 POST repos/를 요청했을 때 3개 이상의 repo를 등록할 수 없다고 뜹니다.

확인 부탁드립니다.

**Comment by joonparkhere** [comment]
엇 그건 의도한 게 맞긴 한데요,
제 의도는 학생이 하나의 과제에 대해 작성할 수 있는 repo 인스턴스는 3개로 제한두는 걸로 이해해서 그렇게 해놓았습니다.

혹시 다르게 생각하시거나 이외의 상황에 에러가 발생하나요?

**Comment by joonparkhere** [comment]
혹시 GET 요청이 `/repos/` URL이 맞다면, 뒤에 쿼리 파라미터로 assignment_id를 같이 전달해주셨나요?
ex. GET `/repos/?assignment_id=1`

**Comment by bw-99** [comment]
헉 그렇네요
감사합니다!!
